// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6YNwZwwxCmJCAejGTjElh3fSIfEq9thQ',
    appId: '1:118659624087:web:864c00d14299e111708dd2',
    messagingSenderId: '118659624087',
    projectId: 'heart-emergency',
    authDomain: 'heart-emergency.firebaseapp.com',
    storageBucket: 'heart-emergency.firebasestorage.app',
    measurementId: 'G-NL82EECW6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5RCecZmKQJa9VOlFYd3KxD4D6Fnwqok',
    appId: '1:118659624087:android:74295f92ca3333e7708dd2',
    messagingSenderId: '118659624087',
    projectId: 'heart-emergency',
    storageBucket: 'heart-emergency.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRwVIG2rkLsFTCugrSZtYjaOSH9D6lo2A',
    appId: '1:118659624087:ios:85910f0975ea751b708dd2',
    messagingSenderId: '118659624087',
    projectId: 'heart-emergency',
    storageBucket: 'heart-emergency.firebasestorage.app',
    iosBundleId: 'com.example.heartEmergency',
  );
}
